# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: nata
      POSTGRES_PASSWORD: 312230

