# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
<<<<<<< HEAD
      - ./docker:/var/lib/postgresql/data
=======
      - ./data:/var/lib/postgresql/data
>>>>>>> 559c5b0d994d5d02035c0ac7a517e791d673c82b
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: nata
      POSTGRES_PASSWORD: 312230

